services:
  - type: web
    name: smart-complaint-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
